name: build cron

on:
  schedule:
    - cron: '30 3,15 * * *'

permissions:
  contents: read
  packages: write

jobs:
  check_update:
    uses: ./.github/workflows/check_update.yml

  vpn_test:
    needs: check_update
    if: needs.check_update.outputs.should_test == 'true'
    uses: ./.github/workflows/vpn_test.yml

  buildx:
    needs: [check_update, vpn_test]
    if: needs.check_update.outputs.should_update == 'true'
    uses: ./.github/workflows/buildx.yml
