name: build

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/main.yml'
      - '.github/workflows/buildx.yml'
      - '.github/workflows/shellcheck.yml'
      - '.github/workflows/vpn_test.yml'
      - '.dockerignore'
      - 'Dockerfile'
      - 'manage.sh'
      - 'run.sh'

permissions:
  contents: read
  packages: write

jobs:
  shellcheck:
    uses: ./.github/workflows/shellcheck.yml

  vpn_test:
    uses: ./.github/workflows/vpn_test.yml

  buildx:
    needs: [shellcheck, vpn_test]
    uses: ./.github/workflows/buildx.yml
